### ISSUE TITLE
Multiple package.json(s)

### ISSUE THREAD

**Issue by johvik** [alanshaw/david-www#104]
Is it possible to get results from a specific directory or even multiple directories in your repo?
For example I got this structure in one of my projects:

server/package.json
client/package.json

If not it would be a nice feature to be able to query something like:
https://david-dm.org/[user]/[repo]/[path]

**Comment by ilkkao** [comment]
+1 I've a repo with 2 package.json files

**Comment by mnquintana** [comment]
:+1: Definitely would love to see this added for the same reasons.

**Comment by lijunle** [comment]
See #160 and #192

**Comment by grabbou** [comment]
We have the same issue in este with 3 repos, common, web, native. CC: @steida. A big +1, if any help is needed, feel free to ping me. Would love to help to make it happen!

**Comment by alanshaw** [comment]
Hi all,

This has landed in david-www@12.0.0
http://davidiswatching.tumblr.com/post/132882415144/non-root-packagejson

Enjoy :smile: :rocket:
