### ISSUE TITLE
Keep user logged in

### ISSUE THREAD

**Issue by ilanbiala** [alanshaw/david-www#159]
When I navigate away from the website, I have to log in again. It would be nice if OAuth would just remember me.

**Comment by ilanbiala** [comment]
@alanshaw have you checked this out?

**Comment by alanshaw** [comment]
Hi @ilanbiala, your enthusiasm is appreciated but I haven't had time to add this in properly. I did look into it initially a while ago and found that using connect-leveldb has further reaching consequences beyond the code you suggest.

**Comment by alanshaw** [comment]
...simply meaning that it's not quite as simple as dropping in your code. A pull request would be greatly appreciated.

**Comment by ilanbiala** [comment]
@alanshaw does leveldb need to be used, or can another db be used instead? What were the issues that you ran into?

**Comment by outaTiME** [comment]
please, im unable to check deps in my private repos =(

**Comment by donny-dont** [comment]
@alanshaw any chance this is related to https://github.com/rvagg/node-generic-session/issues/2? Things seem to time out pretty quick for me and I'm wondering if its related. The current node-level-session package.json is locked to 0.0.2 so it doesn't have the fix.

**Comment by alanshaw** [comment]
Looks like it might be

**Comment by donny-dont** [comment]
@alanshaw I can confirm that this is the issue. I went ahead and ran a `npm shrinkwrap` and then manually modified the value of `generic-session` used to `0.1.1`. I deployed the server and then left for the evening. Coming back in the morning my session was still there.

**Comment by donny-dont** [comment]
@alanshaw dependencies were updated on node-level-session so I think this would be good to go now.

**Comment by alanshaw** [comment]
I've [updated the dependency](https://github.com/alanshaw/david-www/commit/2719213c91aaf71520a3ff54d7810c926fc103cc) and redeployed the site - please let me know if you still see the problem. Thanks for your input everyone on this!
