### ISSUE TITLE
Non-root package.json

### ISSUE THREAD

**Issue by sochka** [alanshaw/david-www#160]
I have a java-webapp. All my JS code including package.json lies in src/main/webapp. Is it possible to somehow tell david-www to look there instead of root package.json?

**Comment by ssmereka** [comment]
:+1: This feature would be helpful!

**Comment by ssmereka** [comment]
Maybe add a URL parameter to specify the package.json path manually, like this:

**Repo's package.json location:**   /server/package.json
**www-david url:**  https://david-dm.org/smartdevicelink/sdl_shaid.svg?manifest=%2Fserver%2Fpackage.json

This would only require to pass in the parameter to the [getManifest](https://github.com/htanjo/david-www/blob/master/lib/profile.js#L64) method and then use it, if specified, [here](https://github.com/htanjo/david-www/blob/master/lib/manifest.js#L74).

**Comment by tomekwi** [comment]
:+1: A must have for monorepo projects like https://github.com/babel/babel, https://github.com/facebook/react or my https://github.com/parametric-svg/-.

**Comment by alanshaw** [comment]
Hi all,

This has landed in david-www@12.0.0
http://davidiswatching.tumblr.com/post/132882415144/non-root-packagejson

Enjoy :smile: :rocket:

**Comment by Offirmo** [comment]
Hi, thanks for this great tool! I can't manage to make this feature works in my monorepo:

https://david-dm.org/offirmo/offirmo-monorepo?path=4-incubator%2Fhello-world-npm

is indeed finding the package.json (displaying the real module name)  but it's missing the dependencies: it says "no dependencies".

**Comment by Offirmo** [comment]
Or maybe it's a cache issue?
