### ISSUE TITLE
Security vulnerabilities in dependencies

### ISSUE THREAD

**Issue by Martii** [alanshaw/david-www#174]
Your badge system appears to be saying there is a vulnerability in the latest [*marked* 0.3.3](https://github.com/chjj/marked/releases) *(again after the 0.3.2 different notification which was updated on our end)*... but [the link](https://nodesecurity.io/advisories/marked_redos) currently points to a "Page not found"... what's up? TIA

---

![david-marked redos](https://cloud.githubusercontent.com/assets/114709/5935219/96e40558-a695-11e4-8a36-0420f06282d0.png)

**Comment by alanshaw** [comment]
Could you post the link for the page on david-dm.org where you're seeing that?

**Comment by alanshaw** [comment]
Looks like there's an advisory here that hasn't been published to the node security project website https://github.com/nodesecurity/nodesecurity-www/blob/master/advisories/marked_redos.md

**Comment by Martii** [comment]
> Could you post the link for the page on david-dm.org where you're seeing that?

![Using David](https://david-dm.org/OpenUserJS/OpenUserJS.org.png) and [above](https://github.com/alanshaw/david-www/issues/174#issue-55731676) I posted [the link](https://nodesecurity.io/advisories/marked_redos) but there it is again. :)

I do think the badge could be a little more non-alarming on the wording like "security advisories" instead of saying our dependencies are "insecure" too... I'm contemplating doing the aggregate below the dispersed now just so it doesn't freak certain people out... but that's a different tangent.

> Looks like there's an advisory here that hasn't been published to the node security project website https://github.com/nodesecurity/nodesecurity-www/blob/master/advisories/marked_redos.md

Great to know... will go do some reading. Thanks.

**Comment by alanshaw** [comment]
Patched for now until the advisory is made public on the website.

**Comment by Martii** [comment]
Thanks... I'll watch for it too.

**Comment by alanshaw** [comment]
@Martii the advisory has now been published https://nodesecurity.io/advisories/marked_redos
