### ISSUE TITLE
Add status bar color meanings to an FAQ

### ISSUE THREAD

**Issue by dotproto** [alanshaw/david-www#186]
## Background

Let me start of by saying I'm new to David. I don't know too much about the project, but I've seen a handful of packages with "dependencies" tags on their GitHub READMEs.

For some reason, though, I keep seeing projects that are "up to date" with yellow tags and I have no idea what that means. 
## User Story

As a user not familiar with David, I want a reference page that describes the various badge states I might encounter so that I can understand and potentially react to the information it's trying to communicate.

**Comment by alanshaw** [comment]
* Green is all up to date
* Yellow is mostly up to date (<25% out of date)
* Red is out of date, or security vulnerability

I'd welcome a PR adding this info somewhere - either on on the hompage, or as a separate page.
