### ISSUE TITLE
Fails to parse GitHub URLs (no badge, no status page)

### ISSUE THREAD

**Issue by Reinmar** [alanshaw/david-www#196]
Check e.g.:

* https://david-dm.org/wwalc/test-7aug-2
* https://github.com/wwalc/test-7aug-2/blob/master/package.json#L29-L30

I would expect that [GitHub URLs](https://docs.npmjs.com/files/package.json#github-urls) will always be green.

**Comment by alanshaw** [comment]
Should now be fixed :)

**Comment by Reinmar** [comment]
Thanks! Confirmed that it works fine.
