### ISSUE TITLE
The service seems to be down

### ISSUE THREAD

**Issue by etiktin** [alanshaw/david-www#197]
The website and the service take forever to load. The shields are broken because of it.
![image 1](https://cloud.githubusercontent.com/assets/4381579/9768552/12131b18-572d-11e5-86c3-d1e58da931c5.png)

**Comment by alanshaw** [comment]
Sorry about that. The site has been steadily getting more and more traffic and I think this has been the reason for the poor response times recently. I've made some architecture changes to deal with the load and hopefully it'll now be better.

**Comment by etiktin** [comment]
Everything seems to be working properly.
Thank you for the quick response and this awesome service :)
