### ISSUE TITLE
Doen't work for repos with dots "." in the name

### ISSUE THREAD

**Issue by wmmihaa** [alanshaw/david-www#202]
Such as https://david-dm.org/microServiceBus/microservicebus.host

**Comment by alanshaw** [comment]
david-dm.org doesn't yet work with non root package.json files, there is a PR open to address this: https://github.com/alanshaw/david-www/pull/192

When I get a second I'll merge and release :(

The issue is not because of the dot!

**Comment by alanshaw** [comment]
https://github.com/alanshaw/david-www/issues/160
