### ISSUE TITLE
[question] use david for non-registered package.json?

### ISSUE THREAD

**Issue by ducin** [alanshaw/david-www#280]
I've got a huge package.json with dependencies defined, but I don't want to publish the package.json, because the project will never be public. I could do an overcome by submitting a npm module with `package.json` file only, but this corrupts npm registry and is a dirty solution.

Is there a way to use david for just package.json files (and not npm registered node modules)?

**Comment by alanshaw** [comment]
You could use the CLI - https://github.com/alanshaw/david

You could create a public github repo with jjust a package.json in it, stripped of everything other than the dependencies and somehow keep it in sync with your project.

**Comment by ducin** [comment]
Cool, perfect, thank you!
