### ISSUE TITLE
ecstatic version 1.4 is classified as insecure

### ISSUE THREAD

**Issue by dotnetCarpenter** [alanshaw/david-www#281]
[ecstatic](https://github.com/jfhbrook/node-ecstatic/releases) version 1.4 is classified as insecure but the security patch has been applied in version 1.4. Only ecstatic < 1.4 suffer the Data crash bug from v8.

https://nodesecurity.io/advisories/ecstatic_illegal-access-crash-from-if-modified-since-header
https://david-dm.org/Firefund/firefund-cli

**Comment by XhmikosR** [comment]
Doesn't seem to happen anymore.

**Comment by alanshaw** [comment]
Please reopen if you notice this again
