### ISSUE TITLE
Request my repo status page gives "Error"

### ISSUE THREAD

**Issue by philipmjohnson** [alanshaw/david-www#285]
Sorry, I'm new to David, but shouldn't this work?

https://david-dm.org/radgrad/datamodel.json?path=app

My repo is:

https://github.com/radgrad/datamodel

with my package.json in the app/ directory.

Thanks for helping a newbie out.

**Comment by alanshaw** [comment]
Is this what you're looking for?
https://david-dm.org/radgrad/datamodel/info.json?path=app

**Comment by philipmjohnson** [comment]
Thanks for the quick reply, and sorry for the confusion. I am hoping for a project page for my project similar to this one:

https://david-dm.org/yoctore/yocto-hint

But 

https://david-dm.org/radgrad/datamodel

Gets an error.

**Comment by alanshaw** [comment]
https://david-dm.org/radgrad/datamodel?path=app

**Comment by philipmjohnson** [comment]
Well, that should have been obvious to me. :) Thanks for helping me out.
