### ISSUE TITLE
`?path=` no longer working

### ISSUE THREAD

**Issue by jescalan** [alanshaw/david-www#303]
See https://david-dm.org/static-dev/spike-tpl-base?path=root as an example -- directory is present in the repo and contains a `package.json` [as seen here](https://github.com/static-dev/spike-tpl-base/tree/master/root).

**Comment by alanshaw** [comment]
That's not a valid JSON file so david-dm can't parse it.

**Comment by jescalan** [comment]
Ah fair enough! Ah well, will have to figure out some other way. Thanks for the quick response!
