### ISSUE TITLE
David website 500 if package.json only has devDeps

### ISSUE THREAD

**Issue by timelf123** [alanshaw/david-www#350]
https://david-dm.org/angulartics/angulartics

The [package.json](https://github.com/angulartics/angulartics/blob/master/package.json) only has devDependencies defined. Is this the reason for the 500? The badge for devDeps seems to work fine

**Comment by alanshaw** [comment]
Should be working now. You have some odd whitespace at the start of your package.json.

**Comment by timelf123** [comment]
Thanks @alanshaw for fixing. I did not spot the whitespace with a cursory glance. If it's not too much trouble can you link the offending line?

**Comment by alanshaw** [comment]
It's the first line, before the `{`

**Comment by timelf123** [comment]
How can I tell? It appears modified in the diff but I can't see any changes
https://github.com/angulartics/angulartics/commit/c8d7387b48594b2cdc208754fa97e5315f2fb76b
