### ISSUE TITLE
Reports none when 17 dev deps and 1 out of date

### ISSUE THREAD

**Issue by rajsite** [alanshaw/david-www#365]
See the following status page: https://david-dm.org/ni/VireoSDK?type=dev

![image](https://cloud.githubusercontent.com/assets/1588923/22798268/ec75795e-eec6-11e6-8e15-a27ef9f4f109.png)

I would expect an orange up to date badge

**Comment by alanshaw** [comment]
ooo, that's not right

**Comment by rajsite** [comment]
@alanshaw I was browsing through and I'm curious if this code: https://github.com/alanshaw/david-www/commit/baf74b82711dd439d7297e24a9bd35b23f2ff810#diff-9ead3d77f16d7f3a8c380c297fa056e4R46

supports branches other than 'master' as the default. Our Github repository is configured for a default branch named 'incoming'.

![image](https://cloud.githubusercontent.com/assets/1588923/22899299/f3d08762-f1ef-11e6-82dd-8db19439e9d1.png)

**Comment by rajsite** [comment]
Also is there a way to specify a specific branch in the badge url? I don't see anything explicit on https://david-dm.org/

**Comment by alanshaw** [comment]
Append the branch name onto the end of the path. e.g.
https://david-dm.org/alanshaw/david-www/no-batch
