### ISSUE TITLE
Internal Server error 

### ISSUE THREAD

**Issue by adamdilibero** [alanshaw/david-www#366]
After signing in & accepting OAuth for GitHub when I browse to my repo on: https://david-dm.org I'm getting a 500 Internal server error 

I've tried removing the OAuth from Github, clearing everything from david-dm.org (Cookies, caches, histories, storage, browsing data) & then re-connecting my github account. 

Same issue persists.

**Comment by aeimer** [comment]
Same Here. Connected with github, added badge to readme get a 'pending' and https://david-dm.org/h-da/geli Throws a 500...

**Comment by OmgImAlexis** [comment]
Same here, can't login at all.

**Comment by dashersw** [comment]
Same here. Can't login.

**Comment by OmgImAlexis** [comment]
@alanshaw is this being looked at?

**Comment by n1ru4l** [comment]
Same for me

**Comment by gabrielcsapo** [comment]
Started it up and configured the github options to point at public github with a new clientId and secret, works fine locally. Might just need to check the configuration on production.

**Comment by OmgImAlexis** [comment]
@gabrielcsapo I replaced the url secrets. This is all I'm getting.

![screen shot 2017-06-02 at 2 21 17 pm](https://cloud.githubusercontent.com/assets/6525926/26815155/d3b067b2-4ac9-11e7-8e8b-166a0a2107b1.png)

**Comment by gabrielcsapo** [comment]
Is that running locally @OmgImAlexis? I am running it locally

**Comment by OmgImAlexis** [comment]
Nope that's the actual site.

**Comment by alanshaw** [comment]
If anyone has time to submit a pull request that would be great!

**Comment by aeimer** [comment]
@alanshaw What should the PR contain? I don't see a solution for this problem in this thread? 
Or should someone debug through this and fix the problem?!

**Comment by alanshaw** [comment]
Error in the server logs:

```
Error: Failed to request access token: Unable to find user from token
    at gh.users.get (/home/david-www/david-www/dist/lib/auth.js:50:23)
    at /home/david-www/david-www/node_modules/github/lib/index.js:894:17
    at callCallback (/home/david-www/david-www/node_modules/github/lib/index.js:728:17)
    at IncomingMessage.<anonymous> (/home/david-www/david-www/node_modules/github/lib/index.js:792:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by OmgImAlexis** [comment]
I've even tried deactivating david-dm in Github's OAuth apps section and logging in again but it still gives me that error. I've used david-dm before so I don't know why this is only happening now.

**Comment by gabrielcsapo** [comment]
Yeah I tried to reproduce the issue locally, I am not seeing it. @alanshaw maybe it is a deploy issue?

**Comment by kamronbatman** [comment]
I am getting the same issue on the actual david-dm.org site.

**Comment by m67hoff** [comment]
I would like to try this but  I am getting the same issue on the actual david-dm.org site

**Comment by jeantimex** [comment]
Same here, cannot sign in to https://david-dm.org, receive "Internal Server Error".

**Comment by broccolini** [comment]
I'm also getting this error 😞

**Comment by andrevenancio** [comment]
still not working

**Comment by raulfdm** [comment]
Browser Log:
```
callback:1 Site cannot be installed: the page has no manifest <link> URL
callback:1 Refused to load the stylesheet 'data:text/css;base64,LyogCiAqIHNodXR1cC5jc3MKICogd2ViIC0gcGVhbnV0IGdhbGxlcn…RhYmxlLmRpZmYgLmNvbW1lbnQKCnsKCWRpc3BsYXk6IGluaXRpYWwgIWltcG9ydGFudDsKfQo=' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

callback Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

**Comment by OmgImAlexis** [comment]
@raulfdm that's not the issue, it's a server side error.

**Comment by raulfdm** [comment]
@OmgImAlexis I know it's, but is the same situation: I try to use OAuth to login and I receive an message `internal server error` and I can't login. I just copy the console log

**Comment by andrevenancio** [comment]
still no progress? :( its just OAuth!!!

**Comment by gabrielcsapo** [comment]
Has anyone been able to reproduce locally? It doesn't look like there is a clear cause

**Comment by OmgImAlexis** [comment]
@gabrielcsapo as per https://github.com/alanshaw/david-www/issues/366#issuecomment-306742465 it looks like it's a Oauth issue. Maybe more logging needs to be added where the stack trace is from.

**Comment by gabrielcsapo** [comment]
will see if I can add PR with that logging, give me 15 minutes 😄

**Comment by gabrielcsapo** [comment]
I think I found the problem

**Comment by gabrielcsapo** [comment]
upon second glance and complete rebase, the issue was the value being received from the get call, https://github.com/alanshaw/david-www/pull/380 should fix the issue 😄

**Comment by alanshaw** [comment]
Thanks @gabrielcsapo 😄

**Comment by aeimer** [comment]
Yep, signing in works again :) Perfect :-*👌

**Comment by gabrielcsapo** [comment]
Yay! :smile:

**Comment by OmgImAlexis** [comment]
That's fixed it. 👍

**Comment by aeimer** [comment]
> Same Here. Connected with github, added badge to readme => 'pending'.
> https://david-dm.org/h-da/geli Throws a 500...

How long do you think David-dm needs to check for new repos? I still get the 500 and the badge is still pending. I have signed in with github. Is it necessary to be a admin of the organisation to add a repo to David dm?
