### ISSUE TITLE
node-pg-migrate erroneously shown as "out of date"

### ISSUE THREAD

**Issue by zartux** [alanshaw/david-www#372]
The image says "dependencies out of date" yet the detailed list says 6 are up to date.

https://david-dm.org/theoephraim/node-pg-migrate

**Comment by jvanbruegge** [comment]
I have the same for my project: https://david-dm.org/cyclejs-community/cyclejs-sortable

**Comment by dolanmiu** [comment]
Same with here:

https://github.com/alanshaw/david-www/issues/367

**Comment by alanshaw** [comment]
Thanks for your patients. I believe this bug has been resolved in by https://github.com/alanshaw/david-www/commit/6436f07bec18384d0d83a8e89b7fb40286da5bc8. Please comment if you notice this issue again.
