### ISSUE TITLE
Support for multi-package repos (rush or lerna repos)

### ISSUE THREAD

**Issue by dzearing** [alanshaw/david-www#374]
We have repos which contain multiple package.jsons. These repos use tools such as @microsoft/rush or lerna to manage installing dependencies, linking, building, and publishing them. [Babel](https://github.com/babel/babel/tree/master/packages), [React](https://github.com/facebook/react/tree/master/packages), [Angular](https://github.com/angular/angular/tree/master/modules), [Ember](https://github.com/emberjs/ember.js/tree/master/packages), [Meteor](https://github.com/meteor/meteor/tree/devel/packages), [Jest](https://github.com/facebook/jest/tree/master/packages), and many others develop all of their packages within a single repository.

For example, same repo, 2 different folders with package.json:

https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react
https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/utilities

Is there a way that David can generate badges for these? At a minimum, just be able to generate a badge for each of the packages, but ideally generate a single badge for the repo's README.md which can track all the dependencies in the entire repo. (If there needs to be some metadata in the root package.json to make that work, cool.)

I tried a few variations without any luck:

https://david-dm.org/OfficeDev/office-ui-fabric-react/packages/office-ui-fabric-react.svg
https://david-dm.org/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react.svg

**Comment by alanshaw** [comment]
https://david-dm.org/OfficeDev/office-ui-fabric-react?path=packages/office-ui-fabric-react
https://david-dm.org/OfficeDev/office-ui-fabric-react?path=packages/utilities

**Comment by dzearing** [comment]
@alanshaw Awesome, thanks!

**Comment by guw** [comment]
@alanshaw Would it be worthwhile to keep that one open as a feature request for parsing lerna.json and coming up with an aggregate status of all packages?

**Comment by daKmoR** [comment]
So having multiple (5+) package.json fils it would be really nice to have an aggregated badge. [Showing 10+ badges (dependencies + devDependencies) will probably defeat its purpose.

However, it seems this might be a bit out of scope for david dm... or is there any plan for something like this? (e.g. search through all files and pick up the package.json ones)
I'm just curious :)
