### ISSUE TITLE
Badges not updating

### ISSUE THREAD

**Issue by eisbehr-** [alanshaw/david-www#377]
Hello,

the badges from my repository are not updating. The dependencies are all up-to-date but the badges showing `insecure` and `out-of-date`. Is there a problem or something I can do to update them?

- https://david-dm.org/eisbehr-/external-ip
[![dependencies Status](https://david-dm.org/eisbehr-/external-ip/status.svg)](https://david-dm.org/eisbehr-/external-ip)

- https://david-dm.org/eisbehr-/external-ip?type=dev
[![devDependencies Status](https://david-dm.org/eisbehr-/external-ip/dev-status.svg)](https://david-dm.org/eisbehr-/external-ip?type=dev)

Thanks!

**Comment by aeimer** [comment]
I can see both badges up there with the text 'up to date'...

**Comment by eisbehr-** [comment]
Yes, now. But this took days! I close this for now ...
