### ISSUE TITLE
Status always pending

### ISSUE THREAD

**Issue by char0n** [alanshaw/david-www#378]
Hi,

Really great service, seems like https://david-dm.org/char0n/ramda-adjunct is always in pending mode. Can you think of any reason why ?

Thank you

**Comment by aivus** [comment]
Hi, @char0n.

I don't see `dependencies` section in 
https://github.com/char0n/ramda-adjunct/blob/master/package.json

It seems the reason of this status.

**Comment by char0n** [comment]
Hi @aivus,

Some time after I reported this issue It started to work on it's own. Then I removed all the dependacies from package.json so I did not need the badge anymore. Thanks anyway. I can close this issue as resolved for now.

**Comment by alanshaw** [comment]
This is a bug which I'm hoping has now been resolved by https://github.com/alanshaw/david-www/commit/6436f07bec18384d0d83a8e89b7fb40286da5bc8. If you don't have dependencies in your `package.json` your badge should be green and read "dependencies none", not pending.
