### ISSUE TITLE
Can't register Github Repo

### ISSUE THREAD

**Issue by aeimer** [alanshaw/david-www#381]
Hi,

so I'm a little confused how to get listed by david-dm...
I'm am talking about the repository: https://github.com/h-da/geli

I went to david-dm.org and signed in with my GitHub-Account, I then added the david-dm badge to the README. This is a few weeks ago and https://david-dm.org/h-da/geli still throws a 500. In realation to #366 I asume that my repo is not watched...

Because I'm not a Admin of h-da/geli We tried to watch our (for travis testing purposes added testing-)fork of the project to david-dm. This works neither. https://david-dm.org/khase/geli

Which rights do I need to have to get watched by david-dm? Am I doing something wrong?

Best regards,
Alex

**Comment by alanshaw** [comment]
https://david-dm.org/khase/geli?path=app/webFrontend
https://david-dm.org/khase/geli?path=api

David looks for `package.json` in the root by default.

**Comment by aeimer** [comment]
Ohhh yeah, got it :/ thank you for your super quick response :)
