### ISSUE TITLE
Superagent dependency 3.7.0 still marked as vulnerable

### ISSUE THREAD

**Issue by jkutianski** [alanshaw/david-www#389]
I updated Superagent to 3.7.x on my package but it's still marked as vulnerable on https://david-dm.org/jkutianski/meetup-api

**Comment by alanshaw** [comment]
At a guess I'd say the advisory had a typo with the vulnerable versions that was updated after it was published. David doesn't automatically update advisories info it already knows about. I've restarted the service (which clears the advisories cache) and your dependency is now showing as not vulnerable.

HTH

**Comment by jkutianski** [comment]
Thanks Alan.
Now it;s OK.
