### ISSUE TITLE
React development build is used in production

### ISSUE THREAD

**Issue by styfle** [alanshaw/david-www#390]
There must be a dev build of React being included on the david-dm.org website because the react dev tools are showing the warning below:

![image](https://user-images.githubusercontent.com/229881/32472992-489ea4ee-c333-11e7-8ffe-c1d451ba9be4.png)

Did you forget to set `NODE_ENV=production` environment variable?

https://github.com/styfle/react-server-example-tsx#deployment

**Comment by alanshaw** [comment]
The [ansible scripts install node modules with the `--production` flag](https://github.com/alanshaw/david-www-infrastructure/blob/master/provision/david-www/tasks/main.yml#L136).

The [`postinstall` script](https://github.com/alanshaw/david-www/blob/master/package.json#L42) runs build and minify.

I can see that the JavaScript _is_ minified: https://david-dm.org/bundle-23.1.0.js

Perhaps the `NODE_ENV` variable needs to also be set? Are you able to verify this is the case @styfle?

**Comment by styfle** [comment]
@alanshaw Correct, you must set `NODE_ENV=production` during build time to get the optimized react output or include the [pre-built UMD script](https://cdn.jsdelivr.net/npm/react@16.2.0/umd/react.production.min.js) as an external.

See the docs here: https://reactjs.org/docs/optimizing-performance.html

**Comment by blgm** [comment]
You need to set `NODE_ENV=production` **and** use dead code elimination using `uglifyify` in order to get this warning to go away.  See PR #399 for details.

**Comment by alanshaw** [comment]
<img width="1248" alt="screen shot 2018-03-03 at 14 10 55" src="https://user-images.githubusercontent.com/152863/36935207-b806c8c4-1eec-11e8-9889-0f506ee08ea6.png">

\o/ thanks all
