### ISSUE TITLE
Incorrectly reporting package vulnerability for patched version of moment.js

### ISSUE THREAD

**Issue by chronosis** [alanshaw/david-www#391]
David is currently incorrectly reporting package vulnerabilities for moment.js version 2.19.3
For example: https://david-dm.org/MediaXPost/logstash-relay

However, the [Node Security Advisory](https://nodesecurity.io/advisories/532) specifically states that this only impacts versions <2.19.3

**Comment by alanshaw** [comment]
Probably the same thing as this: https://github.com/alanshaw/david-www/issues/389#issuecomment-339274960

Fixed now
