### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by johnjohndoe** [alanshaw/david-www#396]
What are the first steps to get _david-dm_ running for a GitHub project?

1. Visit http://david-dm.org
2. Click `Sign in` link in the top left, page updates accordingly
3. _Nothing happens?!_, there is no links to select a project to monitor

**Comment by South-Paw** [comment]
Hi there, unsure if you're still stuck but figured I'd answer anyways.

There isn't really any setup steps... you just add some bits to the URL for your Github project.
The project just needs to have a valid `package.json` and david will do the rest in due course.

For example, one of my projects; https://david-dm.org/South-Paw/discord-music-bot

Badges can be retrieved by adding .svg to the end; https://david-dm.org/South-Paw/discord-music-bot.svg

Hope that helps.

**Comment by johnjohndoe** [comment]
Thank you - this helps. I recommend you put this explanation in the README since it was not obvious to me how to start. Other than that the issue can be closed.

**Comment by alanshaw** [comment]
Would one of you send a PR?

**Comment by South-Paw** [comment]
@alanshaw I don't think you need a PR at all as this is already there in the README...

The example usage right there:

![image](https://user-images.githubusercontent.com/2154764/35590904-21c02776-066d-11e8-99a6-b5ae3b0d07b4.png)

And as the project description states;

```
Node.js based web service that tells you when your project npm dependencies are out of date.
To use David, your project must include a package.json file in your repository.
```

So both of what I stated above.

Sorry, but I honestly just think the reporter just didn't bother to read any of it and made an issue...
