### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by pine** [alanshaw/david-www#407]
Hello. I cannot view my repository status.
It returns Internal Server Error.

<img width="507" alt="screen shot 2018-06-01 at 14 57 43" src="https://user-images.githubusercontent.com/5249050/40823680-322e74f2-65ac-11e8-9224-9be41d35e439.png">

https://david-dm.org/emoji-gen/web-main

Could you know what is wrong? Thank you.

**Comment by alanshaw** [comment]
what's the github url?

**Comment by pine** [comment]
@alanshaw 
This is GitHub URL. `emoji-gen` is my organization.

https://github.com/emoji-gen/web-main

Thank you!

**Comment by alanshaw** [comment]
You have no package.json in the root of your repo.

https://david-dm.org/emoji-gen/web-main?path=frontend - is that what you're looking for?

**Comment by pine** [comment]
@alanshaw Thank you!

**Comment by lealceldeiro** [comment]
The documentation in [**Monorepo or package.json not in root?**](https://github.com/alanshaw/david-www#monorepo-or-packagejson-not-in-root) is kind of misleading. This example is way clearer.
