### ISSUE TITLE
Support non-default branches

### ISSUE THREAD

**Issue by nponeccop** [alanshaw/david-www#426]
Sometimes more than 1 version of a package is maintained (e.g. 2.x and 3.x). So we need separate badges for separate branches. What about supporting `username/repo/branch` in addition to `username/repo` ?

**Comment by SalomonSmeke** [comment]
If I'm understanding you correctly, support for this was added around 4 years ago:

https://davidiswatching.tumblr.com/post/112632310569/branches-and-tags
