### ISSUE TITLE
David is rate-limited

### ISSUE THREAD

**Issue by SFR-git** [alanshaw/david-www#437]
As mentioned in alanshaw/david#174, David is rate-limited and therefore the badge looks like this: ![](https://img.shields.io/badge/dependencies-repo%20or%20path%20not%20found%20or%20david%20internal%20error-lightgrey)

and when clicking over to david-dm.org, this error appears:
```
FetchError: invalid json response body at https://david-dm.org/<username>/<repository>/info.json reason: Unexpected token < in JSON at position 0
    at /home/node/app/node_modules/node-fetch/lib/body.js:48:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
```

Sometimes, instead of `info.json`, it appears as `project.json`, but everything else is the same.

According to [this reply](https://github.com/alanshaw/david/issues/174#issuecomment-736655040) it seems that the problem lies with a deprecated GitHub client that is being used.

The problem fixed itself after a few minutes, *but it's been a frustrating few minutes*.
Is there at least some sort of API token that could be used to up the limit?

**Comment by alanshaw** [comment]
I've deployed a new backend and hopefully this will happen less now. david-dm.org does use an api token and heavily caches responses however there are a lot of requests to make! It's now using a persistent cache so shouldn't run into rate limiting issues when restarting.

**Comment by philihp** [comment]
This appears to have happened again.
