### ISSUE TITLE
Is it possible to specify the path to package.json to check?

### ISSUE THREAD

**Issue by rokumura7** [alanshaw/david-www#439]
Is it possible to specify the path to package.json to check?
In my project which is mono-repository, I cannot get the badge because there is no package.json in the root directory.
Does anyone know how to do this?

**Comment by alanshaw** [comment]
Yep https://davidiswatching.tumblr.com/post/132882415144/non-root-packagejson

**Comment by rokumura7** [comment]
It works✨
Thanks!
