### ISSUE TITLE
private repos

### ISSUE THREAD

**Issue by ralphtheninja** [alanshaw/david-www#44]
Would it be possible to use this on private repositories as well? Perhaps you could authenticate david-www with oath or something so the package.json can be retrieved?

**Comment by ismay** [comment]
Any news on this issue? Is it a `wontfix` because it requires users to give access to private code?

**Comment by rmharrison** [comment]
Any commentary on whether david-dm is 'safe' to use for private repos?

I was appalled when I looked at the authorization request scope:
![accessrequest-david-dm](https://cloud.githubusercontent.com/assets/4275722/18805613/62eb4770-81e0-11e6-9987-1c6707426712.png)

The application doesn't need write access to my repos, so why is he asking!? 

If I'm RTFMing correcting, it doesn't look like github oauth authorization scopes support read-only access [(docs)](https://developer.github.com/v3/oauth/#scopes).

In lieu of github support, is there any type of SLA or privacy policy where david-dm states they won't f*ck my private repos? 

I really would prefer just granting read-access to the `package.json`.

**Comment by dzikowski** [comment]
@rmharrison There seems to be a workaround. You can allow access to public repos only by changing the authorization scope from `repo` to `public_repo` in URL of a page, when GitHub asks for permissions for David.

See: https://superuser.com/questions/1064723/how-to-connect-to-github-only-for-public-repositories

**Comment by rmharrison** [comment]
I'd like to use david-dm for *private* repos. I understand why read is required; write on the other hand...
