### ISSUE TITLE
IE 8 error

### ISSUE THREAD

**Issue by XhmikosR** [alanshaw/david-www#98]
I was trying to make IE 8 work sort of and I hit this error when doing `grunt watch`

```
SCRIPT1010: Expected identifier 
bundle-2.10.0.js, line 12110 character 52
```

This is the line:

```
var handlebars = require('../dist/cjs/handlebars').default;
```

That handlebar directory isn't in dist.

Surprisingly, Firefox and Chrome work.

**Comment by alanshaw** [comment]
Yes, I don't think this is worth investigating!
